name: pebble
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  image_picker: ^1.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/themes/blue_mountains.jpg
    - assets/themes/pink_dawn.jpg
    - assets/themes/green_forest.jpg
    - assets/themes/yellow_sunset.jpg

