#!/usr/bin/env python3
"""Extract user-facing copy from Pebble for the copy review.

Usage (from the repo root):
    python3 docs/review/copy/copy_inventory.py > docs/review/copy/inventory_before.txt

Sources:
  * lib/**/*.dart                string literals that look like UI text
  * web/**/*.html, web/site.js   visible text (tags, scripts and styles removed)
  * supabase/functions/**/*.ts   string literals and template text (emails,
                                 server messages the app shows)
  * docs/store/*.md              store listing copy (whole lines)

It is a heuristic. It skips generated Dart, imports, logging (debugPrint, log,
print, developer.log), keys, routes, storage/analytics identifiers and anything
that looks like code rather than words. Expect a little noise both ways.
"""
import bisect
import html
import os
import re
import sys
from html.parser import HTMLParser

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))

SKIP_LINE = re.compile(
    r"^\s*(import|export|part|library)\b|debugPrint\(|\bprint\(|developer\.log|\blog\(|"
    r"_log\(|ValueKey\(|\bKey\(|GlobalKey|PageStorageKey|assert\(|"
    r"@JsonKey|analytics|logEvent|\.track\(|RegExp\(|DateFormat\(|"
    r"prefs\.(get|set)|\.from\('|\.rpc\(|\.eq\(|\.select\(|\.functions\.invoke|"
    r"Uri\.parse|'package:|throw\s+StateError|throw\s+ArgumentError|"
    r"MethodChannel|EventChannel|invokeMethod|\.json'|\.png'|\.wav'|\.mp3'|fontFamily"
)
DART_STRING = re.compile(
    r"r?'''(?:.|\n)*?'''|r?\"\"\"(?:.|\n)*?\"\"\"|r?'(?:\\.|[^'\\\n])*'|r?\"(?:\\.|[^\"\\\n])*\""
)


def looks_like_copy(s: str) -> bool:
    t = s.strip()
    if len(t) < 2 or not re.search(r'[A-Za-z]', t):
        return False
    words = re.sub(r'\$\{[^}]*\}|\$\w+', 'X', t)
    if re.fullmatch(r'[a-z0-9_.\-/:]+', words):
        return False
    if re.fullmatch(r'[a-z]+[A-Z][A-Za-z0-9]*', words):
        return False
    if re.fullmatch(r'[A-Z0-9_]+', words) and len(words) > 3:
        return False
    if words.startswith(('http', '/', 'assets/', 'package:', 'pebble://', 'mailto:')):
        return False
    if re.fullmatch(r'#?[0-9A-Fa-f]{6,8}', words):
        return False
    if ' ' not in words and not re.match(r'^[A-Z][a-z]', words):
        return False
    return True


def dart_strings(path):
    src = open(path, encoding='utf-8').read()
    lines = src.split('\n')
    offsets, acc = [], 0
    for ln in lines:
        offsets.append(acc)
        acc += len(ln) + 1
    out = []
    for m in DART_STRING.finditer(src):
        lineno = bisect.bisect_right(offsets, m.start())
        line = lines[lineno - 1]
        stripped = line.strip()
        if stripped.startswith(('//', '*', '///')):
            continue
        if SKIP_LINE.search(line):
            continue
        raw = m.group(0)
        if raw.startswith('r'):
            raw = raw[1:]
        q = 3 if raw[:3] in ("'''", '"""') else 1
        body = raw[q:-q]
        after = src[m.end():m.end() + 2]
        if after.startswith(':') and ' ' not in body.strip():
            continue  # map key
        if looks_like_copy(body):
            body = body.replace('\\n', ' / ').replace("\\'", "'").replace('\n', ' ')
            out.append((lineno, body))
    return out


class TextGrab(HTMLParser):
    def __init__(self):
        super().__init__()
        self.skip = 0
        self.chunks = []

    def handle_starttag(self, tag, attrs):
        if tag in ('script', 'style'):
            self.skip += 1
        for k, v in attrs:
            if k in ('alt', 'aria-label', 'placeholder', 'title', 'content') and v and ' ' in v:
                self.chunks.append(f'[{k}] {v}')

    def handle_endtag(self, tag):
        if tag in ('script', 'style') and self.skip:
            self.skip -= 1

    def handle_data(self, data):
        if not self.skip:
            t = ' '.join(data.split())
            if t and re.search(r'[A-Za-z]', t):
                self.chunks.append(t)


def walk(sub):
    for dirpath, dirs, files in os.walk(os.path.join(ROOT, sub)):
        dirs.sort()
        for f in sorted(files):
            yield os.path.join(dirpath, f)


def main():
    out = sys.stdout
    total = 0
    out.write('# Pebble user-facing copy inventory\n')
    out.write('# Generated by docs/review/copy/copy_inventory.py\n\n')

    out.write('## App (lib/)\n')
    for p in walk('lib'):
        if not p.endswith('.dart') or p.endswith(('.g.dart', '.freezed.dart')):
            continue
        items = dart_strings(p)
        if items:
            out.write(f'\n### {os.path.relpath(p, ROOT)}\n')
            for ln, s in items:
                out.write(f'{ln}: {s}\n')
                total += 1

    out.write('\n## Website (web/)\n')
    for p in walk('web'):
        if p.endswith('.html'):
            g = TextGrab()
            g.feed(open(p, encoding='utf-8').read())
            items = g.chunks
        elif p.endswith('.js'):
            items = [b for _, b in dart_strings(p)]
        else:
            continue
        if items:
            out.write(f'\n### {os.path.relpath(p, ROOT)}\n')
            for s in items:
                out.write(html.unescape(s) + '\n')
                total += 1

    out.write('\n## Emails and server messages (supabase/functions/)\n')
    for p in walk(os.path.join('supabase', 'functions')):
        if not p.endswith('.ts') or p.endswith('_test.ts') or '.test.' in p:
            continue
        src = open(p, encoding='utf-8').read()
        items = []
        for m in re.finditer(r"`(?:\\.|[^`\\])*`|'(?:\\.|[^'\\\n])*'|\"(?:\\.|[^\"\\\n])*\"", src):
            body = re.sub(r'<[^>]+>', ' ', m.group(0)[1:-1])
            body = ' '.join(body.split())
            if looks_like_copy(body) and not re.search(r'Deno\.env|Bearer|SELECT|application/', body):
                items.append(body)
        if items:
            out.write(f'\n### {os.path.relpath(p, ROOT)}\n')
            for s in items:
                out.write(s + '\n')
                total += 1

    out.write('\n## Store copy (docs/store/)\n')
    for f in ('GOOGLE_PLAY_LISTING.md', 'APP_STORE_LISTING.md', 'LAUNCH_MARKETING_HOOKS.md'):
        p = os.path.join(ROOT, 'docs', 'store', f)
        if os.path.exists(p):
            out.write(f'\n### docs/store/{f}\n')
            for line in open(p, encoding='utf-8'):
                if line.strip():
                    out.write(line.rstrip() + '\n')
                    total += 1

    out.write(f'\n# Total entries: {total}\n')


if __name__ == '__main__':
    main()
